version: 0.0
os: linux 
files:
  - source: /
    destination: /users/ubuntu/src/logit
hooks:
  ApplicationStop:
    - location: scripts/shutdownserver.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart: 
    - location: scripts/startserver.sh    
      timeout: 300
      runas: root
